name: 'Lock Threads'
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  issues: write
  pull-requests: write
concurrency:
  group: lock
jobs:
  lt:
    runs-on: ubuntu-latest
    steps:
      - name: Locking outdate thread
        uses: dessant/lock-threads@v3
        with:
          issue-inactive-days: '15'
          pr-inactive-days: '15'
          issue-lock-reason: 'resolved'
          pr-lock-reason: 'resolved'
